BOARD_TAG          = Moteino
ARDUINO_DIR        = /Applications/Arduino.app/Contents/Java/
ARDUINO_LIBS       = RFM69 SPIFlash SPI WirelessHEX69 jeelib LinkedList
BOARDS_TXT         = ../boards.txt
MONITOR_PORT       = /dev/cu.usbserial-DA01IIY6
MONITOR_BAUDRATE   = 115200
include ../Arduino-mk/Arduino.mk
